const data = {
    products: [
        {
            _id: '1',
            name: 'Camisa Social',
            slug: 'Camisa-Social',
            categoty: 'camisas',
            image: '/images/p1.jpg',
            price: 100.00,
            countInStock: 0,
            brand: 'Pierre Cardin',
            rating: 3.5,
            numReviews: 5,
            description: 'Camisa social 100% algodão',

        },
        {
            _id: '2',
            name: 'Camisa Social em poliester e algodão',
            slug: 'camisa-social-poliester-algodao',
            categoty: 'camisas',
            image: '/images/p2.jpg',
            price: 89.99,
            countInStock: 10,
            brand: 'Pierre Frabrege',
            rating: 2.5,
            numReviews: 6,
            description: 'Camisa social em poliester e algodão',

        },
        {
            _id: '3',
            name: 'Calça Social Tergal Linho',
            slug: 'calca-social-tergal-linho',
            categoty: 'calcas',
            image: '/images/p3.jpg',
            price: 60.99,
            countInStock: 20,
            brand: 'Lupo',
            rating: 1.5,
            numReviews: 9,
            description: 'Camisa social de botões',

        },
        {
            _id: '4',
            name: 'Calça Social Sport Fino 100% algodão',
            slug: 'calca-social-100-algodao',
            categoty: 'calcas',
            image: '/images/p4.jpg',
            price: 31.99,
            countInStock: 60,
            brand: 'Bruno Mainardi',
            rating: 4.5,
            numReviews: 8,
            description: 'Camisa polo 100% algodão',

        },       
        {
            _id: '5',
            name: 'Vestido Marinho 100% algodão',
            slug: 'vestido-marinho',
            categoty: 'vestido',
            image: '/images/p5.jpg',
            price: 41.99,
            countInStock: 10,
            brand: 'Bruno Mainardi',
            rating: 2.5,
            numReviews: 6,
            description: 'Vestido Marinho com bordados, 100% algodão',

        },       
        {
            _id: '6',
            name: 'Vestido longo de tecido 100% algodão',
            slug: 'vestido-longo-tecido',
            categoty: 'vestido',
            image: '/images/p6.jpg',
            price: 52.99,
            countInStock: 60,
            brand: 'Bruno Mainardi',
            rating: 4.5,
            numReviews: 8,
            description: 'Vestido longo de tecido 100% algodão',

        },       
        {
            _id: '7',
            name: 'Vestido medio de ticlot',
            slug: 'vestido-medio-ticlot',
            categoty: 'vestido',
            image: '/images/p7.jpg',
            price: 81.99,
            countInStock: 30,
            brand: 'Bruno Mainardi',
            rating: 9.5,
            numReviews: 6,
            description: 'Vestido medio de ticlot',

        },       
        {
            _id: '8',
            name: 'Vestido em tecido barra colorido',
            slug: 'vestido-tecido-barra-colorido',
            categoty: 'vestido',
            image: '/images/p8.jpg',
            price: 101.99,
            countInStock: 30,
            brand: 'Bruno Mainardi',
            rating: 1.5,
            numReviews: 2,
            description: 'Vestido em tecido barra colorido',

        },       
    ],
};

export default data;
